export const spells = {
    'bbgaiement': require('@assets/spells/spell-1.png'),
    'franklin': require('@assets/spells/spell-2.png'),
    'patatechaude': require('@assets/spells/potato.png'),
    'megaraman': require('@assets/spells/potato.png'),
    'nalrev': require('@assets/spells/potato.png'),
    'zconome': require('@assets/spells/potato.png'),
    'crayondanslabouche': require('@assets/spells/potato.png'),
    'nonte': require('@assets/spells/potato.png'),
    'ssooooossa': require('@assets/spells/potato.png'),
    'coupdcal': require('@assets/spells/potato.png'),
    'miroirmiroir': require('@assets/spells/potato.png'),
    'antireflet': require('@assets/spells/potato.png'),
    'languefourchue': require('@assets/spells/potato.png'),

    /* bbgaiement: require('@assets/spells/microphone.png'),
franklin: require('@assets/spells/franklin.png'),
patatechaude: require('@assets/spells/potato.png'),
nalrev: require('@assets/spells/nalrev.png'),
megaraman: require('@assets/spells/megaraman.png'),
ssooossa: require('@assets/spells/snake.png'),
coupedecale: require('@assets/spells/pirate.png'),
miroirmiroir: require('@assets/spells/mirror.png'),
caryondanslabouche: require('@assets/spells/pencil.png'),
languefourchue: require('@assets/spells/anti_ss.png'),
antireflet: require('@assets/spells/broken-mirror.png'),
zeconome: require('@assets/spells/peeler.png'),
nonte: require('@assets/spells/nonte.png'), */
};